In [1]:
import numpy as np
from pandas import DataFrame
np.set_printoptions(precision=4)
np.set_printoptions(suppress=True)

In [2]:
f=0
M=np.array([[0.8, 0, 0.4, 1, 0, 0, 1500],
    [0.2, 0.6, 0.44, 0, 1, 0, 715],
    [0, 0.4, 0.16, 0, 0, 1, 190],
    [0.2, 0.3, 0.4, 0, 0, 0, f]], np.float32)
DataFrame(M)

0    1     2    3    4    5       6
0  0.8  0.0  0.40  1.0  0.0  0.0  1500.0
1  0.2  0.6  0.44  0.0  1.0  0.0   715.0
2  0.0  0.4  0.16  0.0  0.0  1.0   190.0
3  0.2  0.3  0.40  0.0  0.0  0.0     0.0

In [3]:
M[:,6]/M[:,0]

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([1875., 3575.,   inf,    0.], dtype=float32)

In [4]:
M[0]=M[0]/0.8
M[1]=M[1]-0.2*M[0]
M[3]=M[3]-0.2*M[0]
DataFrame(M)

0    1     2     3    4    5       6
0  1.0  0.0  0.50  1.25  0.0  0.0  1875.0
1  0.0  0.6  0.34 -0.25  1.0  0.0   340.0
2  0.0  0.4  0.16  0.00  0.0  1.0   190.0
3  0.0  0.3  0.30 -0.25  0.0  0.0  -375.0

In [5]:
M.T[6]/M.T[1]

/usr/lib/python3/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf,   566.6666,   475.    , -1250.    ], dtype=float32)

In [6]:
M[2]=M[2]/0.4
M[1]=M[1]-0.6*M[2]
M[3]=M[3]-0.3*M[2]
DataFrame(M)

0    1     2     3    4     5       6
0  1.0  0.0  0.50  1.25  0.0  0.00  1875.0
1  0.0  0.0  0.10 -0.25  1.0 -1.50    55.0
2  0.0  1.0  0.40  0.00  0.0  2.50   475.0
3  0.0  0.0  0.18 -0.25  0.0 -0.75  -517.5

In [7]:
M.T[6]/M.T[2]

array([ 3750.    ,   549.9999,  1187.5001, -2875.    ], dtype=float32)

In [8]:
M[1]=M[1]/0.1
M[0]=M[0]-0.5*M[1]
M[2]=M[2]-0.4*M[1]
M[3]=M[3]-0.18*M[1]
DataFrame(M)

0    1             2    3     4      5       6
0  1.0  0.0 -5.960464e-08  2.5  -5.0   7.50  1600.0
1  0.0  0.0  1.000000e+00 -2.5  10.0 -15.00   550.0
2  0.0  1.0 -8.940697e-08  1.0  -4.0   8.50   255.0
3  0.0  0.0 -1.490116e-08  0.2  -1.8   1.95  -616.5

In [9]:
M.T[6]/M.T[3]

array([  640.    ,  -220.    ,   255.    , -3082.4998], dtype=float32)

In [10]:
M[2]=M[2]/1
M[0]=M[0]-2.5*M[2]
M[1]=M[1]+2.5*M[2]
M[3]=M[3]-0.2*M[2]
DataFrame(M)

0    1             2             3    4      5       6
0  1.0 -2.5  1.639128e-07  0.000000e+00  5.0 -13.75   962.5
1  0.0  2.5  9.999999e-01  0.000000e+00  0.0   6.25  1187.5
2  0.0  1.0 -8.940697e-08  1.000000e+00 -4.0   8.50   255.0
3  0.0 -0.2  2.980233e-09  1.490116e-08 -1.0   0.25  -667.5

In [11]:
M.T[6]/M.T[5]

array([  -70.,   190.,    30., -2670.], dtype=float32)

In [12]:
M[2]=M[2]/8.5
M[0]=M[0]+13.75*M[2]
M[1]=M[1]-6.25*M[2]
M[3]=M[3]-0.25*M[2]
DataFrame(M)

0         1             2         3         4    5       6
0  1.0 -0.882353  1.928385e-08  1.617647 -1.470588  0.0  1375.0
1  0.0  1.764706  9.999999e-01 -0.735294  2.941176  0.0  1000.0
2  0.0  0.117647 -1.051847e-08  0.117647 -0.470588  1.0    30.0
3  0.0 -0.229412  5.609849e-09 -0.029412 -0.882353  0.0  -675.0